# Generated by Django 4.2.16 on 2024-12-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_delete_oneoffcommand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="owner",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="build",
            name="owner",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="buildprocess",
            name="owner",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="config",
            name="owner",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="release",
            name="owner",
            field=models.CharField(max_length=256),
        ),
    ]
