# Generated by Django 4.2.16 on 2024-12-12 11:27

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0016_auto_20240904_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="creator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
