# Generated by Django 4.2.16 on 2024-12-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pluginscenter", "0026_alter_operationrecord_operator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginreleasestage",
            name="operator",
            field=models.CharField(max_length=256, null=True, verbose_name="操作人"),
        ),
    ]
