# Generated by Django 4.2.16 on 2024-12-12 11:31

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_sandbox", "0002_rename_expire_at_devsandbox_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devsandbox",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
