# Generated by Django 4.2.16 on 2024-12-12 11:31

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("declarative", "0005_remove_deploymentdescription_scripts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdescription",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
