# Generated by Django 4.2.16 on 2024-12-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="operator",
            field=models.CharField(
                help_text="操作者(被编码的 username), 目前该字段无意义", max_length=256
            ),
        ),
    ]
