# Generated by Django 4.2.16 on 2024-12-12 11:22

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_privatetokenholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountfeatureflag",
            name="user",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
    ]
