# Generated by Django 4.2.16 on 2024-12-12 11:31

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("mgrlegacy", "0005_auto_20240606_2254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnativemigrationprocess",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="migrationprocess",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
