# Generated by Django 4.2.16 on 2024-12-12 11:23

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_applicationdeploymentmoduleorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="creator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmembership",
            name="user",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usermarkedapplication",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
