# Generated by Django 4.2.16 on 2024-12-12 11:31

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("ci", "0002_auto_20230807_1727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciatomjob",
            name="operator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
