# Generated by Django 4.2.16 on 2024-12-12 11:29

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcectl", "0011_mig_spec_cls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerrepository",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gitrepository",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sourcepackage",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="svnaccount",
            name="user",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="svnrepository",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
