# Generated by Django 4.2.16 on 2024-12-12 11:26

from django.db import migrations
import paasng.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0023_remove_deployment_hooks_remove_deployment_procfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builtinconfigvar",
            name="operator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True, verbose_name="更新者"
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="operator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="engineapp",
            name="owner",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="moduleenvironmentoperations",
            name="operator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="offlineoperation",
            name="operator",
            field=paasng.utils.models.BkUserField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
